spring.application.name=SpringBootCore2
payment-property.type=razorpay
payment-property.retry-count=5
payment-property.is-enabled=true
payment-property.timeout=3000
# Non-Java file
# Configuration File
# Set values from outside the code

# Configuration file can be .properties or .yaml
# Environment Variables
# Command line arguments
# System properties





